### ISSUE TITLE
Jasmine:ci rake task doesn't work with PhantomJS 2.1.1 (via NPM)

### ISSUE THREAD

**Issue by xtrasimplicity** [jasmine/jasmine-gem#280]
**Problem**
Running `rake jasmine:ci` on a Fedora 25 box with Ruby 2.1.3p242, PhantomJS 2.11 (installed via NPM) results in no specs being executed.

Running `rake jasmine` and checking the results in the web browser (`localhost:8888`) works fine.

**Troubleshooting**
I added the following to `jasmine-2.5.2/lib/jasmine/ci_runner.rb:37`:
```
 puts url
 Signal.trap('INT') { exit 0; }
 sleep
```
and then ran `rake jasmine:ci` from my project
```
[andrew@AndrewsF25Desktop my-project-name]$ rake jasmine:ci
Thin web server (v1.6.3 codename Protein Powder)
Maximum connections set to 1024
Listening on 0.0.0.0:36163, CTRL+C to stop
Waiting for jasmine server on 36163...
jasmine server started

0 specs, 0 failures
http://localhost:36163/?throwFailures=false&random=false
```

When navigating to `http://localhost:36163/?throwFailures=false&random=false`, it doesn't show any specs, and has the following exception logged to the javascript console.
```
Uncaught TypeError: window.callPhantom is not a function
    at PhantomReporter.suiteDone (phantom_boot.js:11)
    at dispatch (jasmine.js:2042)
    at ReportDispatcher.suiteDone (jasmine.js:2013)
    at nodeComplete (jasmine.js:759)
    at onComplete (jasmine.js:2566)
```

I'll create a small rails application to demonstrate this issue.

**Comment by xtrasimplicity** [comment]
It appears that I can't replicate this issue in a test application, so I suspect there might be something wrong with my application itself. I'll close this issue.
